version: '3'
services:
  devcontainer:
    image: rust-dev:latest
    network_mode: host
    privileged: true
    volumes:
      - ../../.vscode-server:/root/.vscode-server
      - ../../.cargo:/root/.cargo
      - ..:/workspaces:cached      
    working_dir: /workspaces
    command: sleep infinity